spring.application.name=manage-users

# ======= Applicazione e DB H2 =======
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ======= Resource Server (JWT) =======
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://idpgw.test4mind.com/realms/demo-interview

# ======= Solo per login via username/password e recupero token (Resource Owner Password) =======
keycloak.token-uri=https://idpgw.test4mind.com/realms/demo-interview/protocol/openid-connect/token
keycloak.client-id=demo-task
keycloak.client-secret=8PDH3fflpbzJyx2rAy39SPB60OuSjeX6
